name: niral_prj
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  animated_splash_screen: ^1.3.0
  image_picker: ^1.1.2
  icons_plus: ^5.0.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.14.0


  # ✅ Add explicit versions:

  firebase_auth_web: ^5.8.11
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your asset directories here, uncomment the ones you need:
  assets:
    - assets/
    - assets/mango/
    - assets/lemon/
    - assets/wheat/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/cropped_image.png"
  adaptive_icon_background: "assets/ph_view.jpg"  # Android only

flutter_native_splash:
  color: "#ffffff"  # Set the background color (optional)
  image: assets/ph_view.jpg  # Full-screen loading splash image
  android: true
  ios: true
  web: false  # Optional, only if you want to configure for web


  # Optional: Add fonts if needed for your app
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
